[Server]
Host = "0.0.0.0"
Port = 8888

[Cache]
Addr = "192.168.1.49:6379"
Pswd = ""

[Mysql]
Dsn = "root:123456@tcp(192.168.1.49:3306)/db_porn?charset=utf8mb4&parseTime=True&loc=Local"

[Email]
Name = "PRON"
SmtpHost = "127.0.0.1"
SmtpPort = "1025"
SmtpUser = "sleepwalkerspace@proton.me"
SmtpPswd = "s__yuOWItvQFu18Ii4x_xw"
Count = 3